apiVersion: 1
deleteDatasources:
  - name: BONDA-TimescaleDB
    orgId: 1
datasources:
  - name: BONDA-TimescaleDB
    uid: bonda-tsdb
    type: grafana-postgresql-datasource
    url: timescaledb:5432
    database: bonda
    user: bonda
    secureJsonData:
      password: bonda
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
